### ISSUE TITLE
 .customThings[0].properties[0].default should be string 

### ISSUE THREAD

**Issue by madb1lly** [WebThingsIO/virtual-things-adapter#52]
Hello @mrstegeman,

In configuration of virtual things add-on, I get this message for any virtual thing for which I do nothing to the default value: " .customThings[0].properties[0].default should be string". 

Screenshot:
![image](https://user-images.githubusercontent.com/25123631/70053095-fc65c700-15d4-11ea-84b9-b0686adad72c.png)

Example steps:
1. Open configuration
2. Change name  of a virtual thing
3.  Apply
4. One message appears for each virtual thing

Note that so far I'm only using OnOffSwitch so I have not tested exhaustively.

**Comment by mrstegeman** [comment]
This is a weird side effect of how we're using the JSON Schema entry for `default` here. Internally, it gets converted to whatever the `type` is set to, so the UI sees the field value as a `boolean`, rather than a `string`. To fix, just type something in the box and then remove it. Or, better yet, type "true" or "false".

I've not come up with a good workaround for this yet, but I'm going to leave this issue open until I do.

**Comment by madb1lly** [comment]
I already have "true" written in the boxes and still get this error. I have to add a space then backspace in the default box each time I am in the config for each virtual thing before I can apply and exit without error.

**Comment by mrstegeman** [comment]
Right, because as I said, it is technically a boolean when first loaded. Modifying the field changes it back to a string.

**Comment by madb1lly** [comment]
Right, I wasn't disagreeing with you, I was just providing extra information in case it was useful.

**Comment by mrstegeman** [comment]
I appreciate it! Like I said, I'm going to keep this open until I can figure out a good way around this in the future.
